### ISSUE TITLE
Does not work in an environment with proxies

### ISSUE THREAD

**Issue by mickfeech** [kejadlen/forecast.alfredworkflow#10]
Does not work in an environment with proxies

**Comment by kejadlen** [comment]
How are your proxies set up? Setting `HTTP_PROXY` in the workflow variables might work, but I don't have a proxy set up to test this on, so I'm not sure if that'll work or not.

**Comment by mickfeech** [comment]
I believe the ruby open_uri calls that are being used would have to be updated to utilize that variable

**Comment by kejadlen** [comment]
Did you try it out?

**Comment by mickfeech** [comment]
Environment variable doesn't work.

**Comment by kejadlen** [comment]
Hm... can you try with both `http_proxy` and `https_proxy`? Ruby's stdlib should use those environment variables by default.
