### ISSUE TITLE
How do I configure this?

### ISSUE THREAD

**Issue by rootwork** [kejadlen/forecast.alfredworkflow#11]
The setup instructions say:

> These environment variables can be configured in Alfred...

and then lists the variables. But HOW do I configure these in Alfred? The old `forecast-config` and `config-forecast` keywords don't exist. The only thing I see in the workflow is "forecast" and I don't see any obvious place for me to set variables. Typing `forecast` attempts to retrieve weather information and fails, I presume because I haven't been able to enter any API keys.

Can you provide a little more guidance on how these get configured now? Thanks!

**Comment by kejadlen** [comment]
Are you on Alfred 2 or 3? Version 1.0.5+ requires Alfred 3, but 1.0.4 and below should still support Alfred 2.

**Comment by rootwork** [comment]
Alfred 3. Sorry for not specifying!

**Comment by kejadlen** [comment]
In that case, this might help: https://www.alfredapp.com/help/workflows/advanced/variables/

**Comment by rootwork** [comment]
Thanks. The link to the documentation is indeed what I was hoping for. Appreciate it!
